### PR TITLE
update versions and dates

### PR DESCRIPTION
**Pull request by SethTisue**
Scala open source spree, Copenhagen, 2017

### CODE REVIEW

**Comment by SethTisue** [comment]
@noelwelsh I see a `.travis.yml` in the repo, but Travis doesn't seem to be enabled in the repo. may I suggest enabling it? if it fails, I can try and help sort it out

**Comment by SethTisue** [comment]
Travis seems to be working now, we'll see if it builds though...

**Comment by SethTisue** [comment]
the Travis build failures due to Typelevel Scala date back to https://travis-ci.org/underscoreio/doodle/builds/166694990 — but in that run, the failure was because of some `-Ypartial-unification` thing, not unresolved dependencies

perhaps the unresolved dependencies are because of the move to 2.12.2 — I think Typelevel Scala recently started using a different version number format? in any case, @noelwelsh said (in person) that it's fine to go back to regular Scala

**Comment by SethTisue** [comment]
Travis is green now — so I think this is ready for merge?

**Comment by noelwelsh** [comment]
LGTM! Thanks!

**Pull request merged**
