### PR TITLE
Add 'at' layout combinator

### PR DESCRIPTION
**Pull request by noelwelsh**
Example

Circle(5) at (20, 20) on Circle(10)

This combinator allows you to layout an element at any position relative to
the local origin. This adds additional flexibility beyond what
on/above/beside offer, at the cost of more work for the user is
calculating layouts.

At layout also expands the bounding box to include the offset.

### CODE REVIEW

**Comment by noelwelsh** [comment]
I thought about introducing a type for points, but I decided against it for two reasons:

- it's only needed in one place
- it's possibly extra hoops for beginners to jump through

I'm on the fence about this. I imagine if we had more elaborate transformation we'd want such types.

**Comment by davegurnell** [comment]
I see what you mean. Ok - let's try tuples. On the minus side, they are also a new thing for people to learn (and arguably something that's odder than custom types). However, on the plus side, experience with tuples might be useful for people.

I have similar reservations about other types:

 - `Normalised` isn't particularly intuitive. I'd prefer it if (a) conversion from `Double` to `Normalised` was automatic (implicit conversion), (b) we dropped it altogether, or (c) we made it part of the renderer to keep it out of user code.

 - `UnsignedByte` is similarly overkill. Would `Int` be a suitable alternative?

**Comment by noelwelsh** [comment]
There is a difference between `Normalised` and `UnsignedByte`, and a `Point` type (represented implicitly or explicitly), which is that the entire domain of `(Double, Double)` is a valid point but this is not the case for the other types and the equivalent basic numeric types they wrap.

Having those types found some errors in the color management code, and I would like to keep them around as an example of designing using types.

For `At` it is possible to use a `Point` type internally and still expose the current interface because there is no conversion needed from two `Double`s to a `Point` (other than wrapping) so no need for the user to express how the conversion should be performed. I'll look at doing this.

**Comment by davegurnell** [comment]
Don't worry about introducing `Point` for internal use. The code is fine as it is. I'm purely concerned with writing the code in such a way as to not flood people with ideas.

I've added some predefined `Colors` so we can leave `Normalised` until later in the course. In that context it'll be beneficial to talk about types-as-error-handling, rather than being a distraction from doing interesting stuff.

**Pull request merged**
